### PR TITLE
Implement autocheck model

### PR DESCRIPTION
**Pull request by maghuro**

### CODE REVIEW

**Comment by jkychn** [comment]
@maghuro, I had a quick look at your work and it all looks great :) Thanks so much!

Normally we work in the develop branch but what I'll do is merge your requests then rename the updated file to cake-qos-dev.sh and commit cake-qos.sh again with the currently live code. This way people don't accidentally download the development version. This also avoids you having to resubmit all your pull requests to the develop branch.

Does this sound okay?

**Comment by ttgapers** [comment]
> 
> 
> @maghuro, I had a quick look at your work and it all looks great :) Thanks so much!
> 
> Normally we work in the develop branch but what I'll do is merge your requests then rename the updated file to cake-qos-dev.sh and commit cake-qos.sh again with the currently live code. This way people don't accidentally download the development version. This also avoids you having to resubmit all your pull requests to the develop branch.
> 
> Does this sound okay?

Sounds good to me. I a mentioned to @maghuro that I am ok bringing him onboard (similar to how we started), and we can all work as we have via develop->master->releases which have been managed for the most part by @jkychn 

Once we are all good, I can add @maghuro - so do let me know.

**Comment by maghuro** [comment]
> @maghuro, I had a quick look at your work and it all looks great :) Thanks so much!
> 
> Normally we work in the develop branch but what I'll do is merge your requests then rename the updated file to cake-qos-dev.sh and commit cake-qos.sh again with the currently live code. This way people don't accidentally download the development version. This also avoids you having to resubmit all your pull requests to the develop branch.
> 
> Does this sound okay?

Yes, please, do it. And Thanks!

In the future i'll pull request to the dev branch - however, it has to be in sync with master, because of conflits :)

**Comment by jkychn** [comment]
> Once we are all good, I can add @maghuro - so do let me know.

Definite yes from me, and thanks @maghuro! Will do shortly, I'll update develop/cake-qos.sh with your code instead of master/cake-qos-dev.sh, will comment here once done.

**Comment by jkychn** [comment]
@maghuro @ttgapers all done!

Fixed a minor thing (extra parameters): https://github.com/ttgapers/cakeqos-merlin/blob/develop/cake-qos.sh#L139

If ${options} is quoted, cake will not be applied properly because the options are not properly expanded.

The development v0.0.5 can be downloaded and tested using:

`/usr/sbin/curl --retry 3 "https://raw.githubusercontent.com/ttgapers/cakeqos-merlin/develop/cake-qos.sh" -o "/jffs/scripts/cake-qos" && chmod 0755 /jffs/scripts/cake-qos`

**Comment by ttgapers** [comment]
Gonna give it a whirl on my lunch break and let you know if I have any issues. Will add @maghuro as a CakeQOS-Merlin contributor! Awesome work all!

**Comment by ttgapers** [comment]
> 
> 
> Gonna give it a whirl on my lunch break and let you know if I have any issues. Will add @maghuro as a CakeQOS-Merlin contributor - **already done**! Awesome work all!

Clean install

`/tmp/home/root# /usr/sbin/curl --retry 3 "https://raw.githubusercontent.com/ttgapers/cakeqos-merlin/develop/cake-qos.sh" -o "/jffs/scripts/cake-qos" && chmod 0755 /jffs/scripts/cake-qos
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12217  100 12217    0     0  19673      0 --:--:-- --:--:-- --:--:-- 20671
admin@sauron:/tmp/home/root# /jffs/scripts/cake-qos enable 145Mbit 14Mbit "besteffort docsis ack-filter"
CakeQOS-Merlin: Stopping

Broadcom Packet Flow Cache learning via BLOG enabled.
CakeQOS-Merlin: Enabled

CakeQOS-Merlin: Starting - settings: 145Mbit | 14Mbit | besteffort docsis ack-filter

Broadcom Packet Flow Cache learning via BLOG disabled.
Broadcom Packet Flow Cache flushing the flows
admin@sauron:/tmp/home/root# tc -s qdisc show dev ifb9eth0
qdisc cake 8017: root refcnt 2 bandwidth 145Mbit besteffort triple-isolate nat wash ingress ack-filter split-gso rtt 100.0ms noatm overhead 18 mpu 64 no-sce
 Sent 4462946 bytes 9099 pkt (dropped 4, overlimits 1806 requeues 0)
 backlog 0b 0p requeues 0
 memory used: 24256b of 7250000b
 capacity estimate: 145Mbit
 min/max network layer size:           46 /    1500
 min/max overhead-adjusted size:       64 /    1518
 average network hdr offset:           14

                  Tin 0
  thresh        145Mbit
  target          5.0ms
  interval      100.0ms
  pk_delay        2.0ms
  av_delay        214us
  sp_delay          0us
  backlog            0b
  pkts             9103
  bytes         4469002
  way_inds            0
  way_miss          121
  way_cols            0
  marks               0
  drops               4
  ack_drop            0
  sp_flows            1
  bk_flows            1
  un_flows            0
  max_len          1514
  quantum          1514
`

**Pull request merged**
