### PR TITLE
Update cake-qos.sh

### PR DESCRIPTION
**Pull request by jumpsmm7**
Adjustment to Update Function.

### CODE REVIEW

**Comment by jumpsmm7** [comment]
It is not required to be there but it is to follow the same logic as the following joint arguements of !=. it holds more of an absolute than = alone.

**Comment by jkychn** [comment]
I think == should be changed to =, I'm getting:

./cake-qos: 71: [: v0.0.6: unexpected operator

Error gone if =.

**Comment by maghuro** [comment]
IMHO checking for both MD5 and versioning changes on both if and elif, isn't totally necessary

**Comment by maghuro** [comment]
So I think this change isn't totally needed

**Comment by jumpsmm7** [comment]
It is beneficial as it allows it to not blindly update because github is acting funky which will reduce user confusion.

**Comment by jumpsmm7** [comment]
I have made per requested adjustments. the == argument conflicts because of you are only comparing numeric values.

**Comment by jkychn** [comment]
Thank you @jumpsmm7 and @maghuro!

**Pull request merged**
