### PR TITLE
New WebUI for 386.2 FW with Cake built-in

### PR DESCRIPTION
**Pull request by dave14305**
This is an alpha version of a CakeQoS WebUI interface which exposes many of CAKE's options and allows free-form input of any obscure options.

Non-default settings are saved to custom_settings.txt and the redesigned shell script processes these options into a `/jffs/configs/cake-qos.conf.add` file that overrides the firmware CAKE settings.

Applying settings causes QoS to restart, and the conf.add contents to be appended to `/etc/cake-qos.conf`, which is then sourced by `/tmp/qos` to initialize CAKE with our settings.

Future versions will incorporate iptables rules with DSCP classes, and dnsmasq ipset-based rules comparable to the OpenWRT Ultimate SQM Settings script.

### CODE REVIEW

**Comment by dave14305** [comment]
If accepted, please squash the commits with "Squash and merge"

**Comment by ttgapers** [comment]
Thanks will deal with any Travis issues later.

**Review by ttgapers — COMMENTED** [review]
All good

**Comment by dave14305** [comment]
I'm not a fervent believer in POSIX compliance for scripts meant to run on only one operating system.

**Pull request merged**
