### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by maghuro**

### CODE REVIEW

**Comment by maghuro** [comment]
As Adamm00 said, users must have to unninstall, remove and install this new release.

I think we're ready for v1.0.0 so, after merge this, we've to say that on SNBForums and change the release number for 1.0.0 and branch developer to master

**Comment by Adamm00** [comment]
If you wouldn't mind it would make it much easier to continue my work if you gave me collaborator permissions, with multiple people working on the script its quite hard to keep my local branch up to date or submit minor fixes without rebasing and pull requests.

**Comment by maghuro** [comment]
> If you wouldn't mind it would make it much easier to continue my work if you gave me collaborator permissions, with multiple people working on the script its quite hard to keep my local branch up to date or submit minor fixes without rebasing and pull requests.

I agree. In fact, i've already thought on that.
I can't do it, but @ttgapers please do it

**Comment by ttgapers** [comment]
> 
> 
> If you wouldn't mind it would make it much easier to continue my work if you gave me collaborator permissions, with multiple people working on the script its quite hard to keep my local branch up to date or submit minor fixes without rebasing and pull requests.

Yes sir...invite sent, more than happy to have you on board. @maghuro if it helps to get @jackyaz added as well I am 100% onboard.

**Comment by maghuro** [comment]
> > If you wouldn't mind it would make it much easier to continue my work if you gave me collaborator permissions, with multiple people working on the script its quite hard to keep my local branch up to date or submit minor fixes without rebasing and pull requests.
> 
> Yes sir...invite sent, more than happy to have you on board. @maghuro if it helps to get @jackyaz added as well I am 100% onboard.

Be my guest :)

**Comment by maghuro** [comment]
> 1|"") does nothing. Not sure what your goal is here

as this is the default option, if user press "enter" without choosing an option, it'll choose the first one.

I tested it and it worked withouth choosing option :/

**Comment by maghuro** [comment]
> This isn't how the config system works, the values are already loaded, they don't need to be called again.

Sorry, misunderstood the working method here.
I made another script where I call the vars that way from another file, another aproach. thanks

**Comment by ttgapers** [comment]
> 
> 
> > > If you wouldn't mind it would make it much easier to continue my work if you gave me collaborator permissions, with multiple people working on the script its quite hard to keep my local branch up to date or submit minor fixes without rebasing and pull requests.
> > 
> > 
> > Yes sir...invite sent, more than happy to have you on board. @maghuro if it helps to get @jackyaz added as well I am 100% onboard.
> 
> Be my guest :)

@jackyaz added - invite sent.

**Comment by maghuro** [comment]
@ttgapers @jkychn 
please make the honours on SNB.

Remember to say that is needed to unninstal the current version and install this new one with:

**sh -c "$(curl -sL https://raw.githubusercontent.com/ttgapers/cakeqos-merlin/master/cake-qos.sh)" -s installer**

Let's stick with this code for now, as it is shorter and cleaner.

**Comment by Adamm00** [comment]
Personally I strongly disagree with this change, no other script does it this way. Adding another variation of an install command causes unnecessary confusion. The install process is already one copy and pasted command, no need to over engineer things. If we are going to take this project seriously, we need to stick to the Merlin scripting guidelines that have been in place for years.

**Comment by ttgapers** [comment]
> 
> 
> Personally I strongly disagree with this change, no other script does it this way. Adding another variation of an install command causes unnecessary confusion. The install process is already one copy and pasted command, no need to over engineer things. If we are going to take this project seriously, we need to stick to the Merlin scripting guidelines that have been in place for years.

Those guidelines I am seeing for myself here, and appreciating this learning experience!

**Pull request merged**
